name: PTP Always Active Sessions

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"   # हर 6 घंटे पर restart होगा

jobs:
  keep-browser:
    runs-on: ubuntu-latest
    timeout-minutes: 360     # हर job 6h तक चलेगा
    strategy:
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] # 20 jobs
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run 10 permanent sessions
        run: |
          node <<'EOF'
          const puppeteer = require('puppeteer');

          (async () => {
            const browser = await puppeteer.launch({
              headless: true,
              args: ['--no-sandbox']
            });

            const baseUrl = "https://adnade.net/ptp/?user=gurusingh&subid=";

            // Open 10 pages and keep them alive
            for (let i = 1; i <= 10; i++) {
              browser.newPage().then(async (page) => {
                const subid = (process.env.MATRIX_JOB_ID - 1) * 10 + i;
                await page.goto(baseUrl + subid, { waitUntil: "networkidle2" });
                console.log(`✅ Job ${process.env.MATRIX_JOB_ID}: Session ${i} active with subid=${subid}`);
              });
            }

            // Keep Node alive until job timeout (~6h)
            setInterval(() => {}, 1000);
          })();
          EOF
        env:
          MATRIX_JOB_ID: ${{ matrix.job_id }}
